# Generated by Django 3.2.12 on 2022-07-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_alter_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('country', models.CharField(max_length=30)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author_name', to='book_app.book')),
            ],
        ),
    ]
