# Generated by Django 3.2.12 on 2022-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_auto_20220723_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='author/no-photo.jpg', upload_to='author/'),
        ),
    ]
