# Generated by Django 3.2.12 on 2022-09-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0011_author_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='Нет описания'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book/no-image.jpeg', upload_to='book/'),
        ),
    ]
